# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  # This service will extend code from dcape
  app:
    environment:
      COLLECTIONS: "crowdsecurity/nginx"
      GID: "${GID-1000}"
      PGUSER
      PGPASSWORD
      PGDATABASE
    volumes:
      - ${APP_ROOT}/db:/var/lib/crowdsec/data
      - ${APP_ROOT}/config:/etc/crowdsec
      #- ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      #- logs:/var/log/nginx
